source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in werewolf-api.gemspec
gemspec

gem 'faker', :git => 'https://github.com/faker-ruby/faker.git', :branch => 'master'
gem 'sinatra'
gem 'aws-record'
gem 'jwt'
gem 'rack'
gem 'rack-test'
gem 'dotenv-rails'
gem "sinatra-cross_origin", "~> 0.3.1"